### ISSUE TITLE
Omit first comma in the script calls without parentheses

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript-parser#42]
In coffeescript, they call functions as `a b, c, d` which translates to `a(b, c, d)`. We call them with `a, b, c, d`, i.e. without the comma after the function name. IMO, Coffeescript's approach is nicer. Should we apply it?

**Comment by AndreVanDelft** [comment]
The problem with the coffeescript syntax is that the space has already the meaning of sequence.
I originally had 
```
a,b
```
in mind in case this would constitute a tuple for which an implicit conversion could exist.
E.g. in a syntax description where a is a syntactic element, and b a modifier, for instance for spacing.
Then such syntax could also apply for a call to ```a``` with parameter ```b```.

But a syntax with colons could be much more attractive, in combination with script blocks between rectangular brackets. Then the parentheses would be available to create tuples, e.g. ```(a,b)```.

So I am now more for a Smalltalk like syntax for function&method calls, with comma's for the function parts that come after the first one. E.g.,
```
p: a,b,c,d
```
and
```
p:a, q:b, r:c
```
I'd say FTTB do not change much; let's first program a few use cases.

**Comment by anatoliykmetyuk** [comment]
Ok, but just to make it clear FTTB: there aren't supposed to be any spaces in the args list at all? Becase current implementation allows arbitrary expression for every argument, without new lines. If you want to write it in sequence with other operands, you wrap it into parentheses: `a (b, c, d) e` is same as `a b(c, d) e`.

PS: I still think colons and square braces are not a good idea: too much confusion with type specification, too much deviation from convention. But I agree, we should have use cases once the core part is ready.
