### ISSUE TITLE
Child of `if` operator

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript-parser#44]
Currently, by mistake, the parser parses Expr9 as a child of the `if` operator. This means, least-priority operator of `then` section of `if` is an indented newline.

This enables a nice syntax like:
```scala
if condition then a b
                  c d
else a b
     e f
```

But this:
```scala
if condition then a else b ; c
```
parses like `if(condition)(a, seq(b, c))`, instead of `seq(if(condition)(a, b), c)`.

If we don't allow Expr9 to be parsed as the child of `if`, we'll disable the nice syntax with indented new lines as arguments to `if`. So, the first example will need to be written as:
```scala
if condition then (a b
                  c d)
else (a b
     e f)
```

IMO, it is much nicer in its current form, since uses indentation to replace parentheses. Should we preserve this behaviour, or should we stick to the old one?

**Comment by AndreVanDelft** [comment]
IMO it is essential that combinations of (if, ;, +) behave the same as in Scala. So let's stick to the old behaviour.
BTW I had underestimated the pecularities of "if" myself, resulting in a really inconsistent parser during the second half of 2014.
